project:
  type: website
  output-dir: docs
  execute-dir: project #file is other option
  resources: src
  render:
    - index.qmd
    - _abstract.qmd
    - _intro.qmd
    - _methods.qmd
    - _results.qmd
    - _discussion.qmd
    - _acknowledgements.qmd
    - _references.qmd
    - _colophon.qmd

execute:
  freeze: auto
