project:
  type: website
  output-dir: docs
  execute-dir: file # project #file is other option
  # resources: src
  render:
    - index.qmd
    - _00_abstract.qmd
    - _01_intro.qmd
    - _02_methods.qmd
    - _03_results.qmd
    - _04_discussion.qmd
    - _05_acknowledgements.qmd
    - _06_references.qmd
    - _colophon.qmd

execute:
  freeze: auto
