project:
  title: "rrtools"
  output-dir: docs
  execute-dir: file #project # file is other option
  resources: src
  render:
    - analysis/paper/index.qmd
    - "!analysis/paper/paper.qmd"
    # - "*.qmd"
    # - "!ignored.qmd"
    # - "!ignored-dir/"

execute:
  freeze: auto
